name: "Run Craftos"
description: "Runs a CraftOS computer as a Headless CI"
inputs:
  root:
    description: "root of the computers relative to repository root"
    required: false
    default: "."
  timeout:
    description: "maximum ammount of time in seconds for CraftOS to run before erroring"
    required: true
    default: "60"
  args: 
    description: "string to pass into the --args of CraftOS"
    required: false
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.root}}
    - ${{inputs.timeout}}
    - ${{inputs.args}}